
export const EVENT_CONFIG_DETAILS = "EVENT_CONFIG_DETAILS";

export const EVENT_PARTICIPANTS_DETAILS = "EVENT_PARTICIPANTS_DETAILS";

export const EVENT_ID = "EVENT_ID";

export const EVENT_ENCRYPTED_ID = "EVENT_ENCRYPTED_ID";

export const EVENT_PARTICIPANTE_RESPONSE_DATA = "EVENT_PARTICIPANTE_RESPONSE_DATA";


